# Introduction to Scipy

In this notebook, I added basic ways to use the Scipy library.

For context, Scipy is an est open-source library of scientific calculus in Python and it is based of Numpy. With Scipy, we can do linear algebra, statistics, signal treatment and many other things. 

## Importing the necessary libraries 
We should always start by importing the libraries we need to make our porgram work.

It is highly recommended to not use ```import scipy``` . Instead, we can specify what we want to import. For example we can write : 

```from scipy import constants```

In [1]:
import numpy as np
from scipy import constants, optimize, stats, linalg
from scipy.constants import pi, speed_of_light
from scipy.linalg import inv, solve, svd, norm, det, ishermitian, hadamard

## Calculus

For some reason, your physics professor asked you to calculate $$π * \text{speed of light}$$ You can do it with the help of scipy: 

In [2]:
# calculate pi * speed of light

result = pi * speed_of_light
print ("the resultat is:", result)

the resultat is: 941825783.6544266


### Linear Algebra

We can also use Scipy to do linear algebra. 

We will start by using numpy to create a matrix:

In [3]:
A = np.array([[1,2],
              [3,4]]) # a matrix numpy 2x2 of your choice

print("Matrix A:\n", A)

Matrix A:
 [[1 2]
 [3 4]]


Now, you can inverse the matrix A using ```linalg``` of scipy :

In [4]:
A_inv = inv(A) # inverser A avec scipy

print("Matrix A inversed:\n", A_inv)

Matrix A inversed:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Solving an equation system
We can solve this equation with scipy $$Ax = B.$$

We need to initialize a vector B first.

In [5]:
B = np.array([1,2]) # initializing B

x = solve(A, B) # solving equation with scipy
print ( " the solution to this equation is: ", x)

 the solution to this equation is:  [0.  0.5]


We can now find the eigenvalues and the eigenvectors of our matrix A

In [6]:
eigenvalues, eigenvectors = np.linalg.eig(A) # using scipy to find the proper values and vectors of a matrix

print ("the eigenvalues of A are: ", eigenvalues)
print ("the eigenvectors of A are: ", eigenvectors)

the eigenvalues of A are:  [-0.37228132  5.37228132]
the eigenvectors of A are:  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


we can also do a the singular value decomposition of a matrix (SVD) with Scipy.

In [7]:
# using scipy to do an SVD
x, y, z = svd(A)

# showing results
print("Matrice X (singular vectors on the left ) :\n", x)
print("\nsingular vectors (singular values on the diagonal) :\n", np.diag(y))
print("\nMatrix Z (singular values on the right) :\n", z)

Matrice X (singular vectors on the left ) :
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

singular vectors (singular values on the diagonal) :
 [[5.4649857  0.        ]
 [0.         0.36596619]]

Matrix Z (singular values on the right) :
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


We can also calculate the norm of a matrix with scipy:

In [8]:
# calculating the norm of our matrix A
norm = norm(A)

print("the norm of our matrix A is: ", norm)

the norm of our matrix A is:  5.477225575051661


we can also calculate the determinant of our matrix:

In [9]:
# calculate the determinant of A
determinant = det(A)

print("the determinant of A is :", determinant)

the determinant of A is : -2.0


Scipy also allows us to verify if our matrix is hermitian or not:

In [10]:
est_hermitienne = ishermitian(A)

if est_hermitienne == False:
    print (" the matrix is not hermitian")
else:
    print (" the matrix is hermitian")

 the matrix is not hermitian


In addition, we can create a Hadamard matrix with Scipy. We can also choose the size of this matrix

In [11]:
n=2 # desired size for the matrix

# using scipy to generate a Hadamard matrix
H = hadamard(n)

print(H)

[[ 1  1]
 [ 1 -1]]
